// client/src/components/blog/BlogList.vue
<template>
	<div class="l-blog-list">
		<BlogPost
			v-for="blogpost in blogPosts"
			:key="blogpost.id"
			:id="blogpost.id"
			:title="blogpost.title"
			:date="blogpost.date"
			:preview-image="blogpost.previewImage"
			@onDelete="onBlogItemDelete"
		/>
	</div>
</template>

<script lang="ts">
import { defineComponent } from "vue"
import BlogPost from "@/components/blog/BlogPost.vue"

export default defineComponent({
	name: "BlogList",
	components: { BlogPost },
	props: {},
	methods: {
		onBlogItemDelete(id: number) {
			console.log("OnDelete triggered for id:", id)
			for (let i = 0; i < this.blogPosts.length; i++) {
				if (this.blogPosts[i].id == id) {
					this.blogPosts.splice(i, i) //remove item from array
					break
				}
			}
		}
	},
	data() {
		return {
			blogPosts: [
				{
					id: 1,
					title: "Big Article A",
					date: "Dec 2021",
					previewImage: "https://picsum.photos/seed/randi/300/200"
				},
				{
					id: 2,
					title: "Big Article B",
					date: "Dec 2021",
					previewImage: "https://picsum.photos/seed/other/300/200"
				},
				{
					id: 3,
					title: "Big Article C",
					date: "Dec 2021",
					previewImage: "https://picsum.photos/seed/test/300/200"
				}
			]
		}
	}
})
</script>

// client/components/blogList.jsx
import React, { Component } from "react";
import BlogPost from "./blogPost";

class BlogList extends Component {
    state = {
        blogposts: [
            {
                id: 1,
                img_src: "https://picsum.photos/seed/randi/300/200",
                title: "Big Article A",
                date: "Dec 2021",
            },
            {
                id: 2,
                img_src: "https://picsum.photos/seed/other/300/200",
                title: "Big Article B",
                date: "Dec 2021",
            },
            {
                id: 3,
                img_src: "https://picsum.photos/seed/test/300/200",
                title: "Big Article C",
                date: "Dec 2021",
            },
        ],
    };

    handleDeleteArticle = (postId) => {
        const blogposts = this.state.blogposts.filter(
            (pid) => pid.id !== postId
        );
        this.setState({ blogposts });
    };

    render() {
        return (
            <div className={"l-blog-list"}>
                {this.state.blogposts.map((blogpost) => (
                    <BlogPost
                        key={blogpost.id}
                        blogpost={blogpost}
                        onDelete={this.handleDeleteArticle}
                    />
                ))}
            </div>
        );
    }
}

export default BlogList;
